In [1]:

# Student Result Analysis using NumPy
import numpy as np

data = np.array([
    [78, 85, 80, 90, 1],
    [45, 50, 40, 55, 0],
    [18, 72, 94, 95, 1],
    [50, 95, 40, 58, 1],
    [75, 70, 68, 52, 0],
    [80, 35, 38, 91, 1],
    [25, 78, 90, 72, 1],
    [98, 15, 50, 87, 0],
    [42, 55, 88, 80, 1],
    [60, 25, 88, 60, 0]
])


X = data[:, :-1]
y = data[:, -1]

print("Features (X):")
print(X)

print("\nLabels (y):")
print(y)


print("\nAverage Marks:")
print(np.mean(X, axis=0))

print("\nMaximum Marks:")
print(np.max(X, axis=0))

print("\nMinimum Marks:")
print(np.min(X, axis=0))


passed = np.sum(y == 1)
failed = np.sum(y == 0)

print("\nNumber of Passed Students:", passed)
print("Number of Failed Students:", failed)


above_80 = X[X > 80]

print("\nMarks Above 80:")
print(above_80)


below_50 = X[X < 50]

print("\nMarks Below 50:")
print(below_50)

X_normalized = (X - np.min(X, axis=0)) / (
    np.max(X, axis=0) - np.min(X, axis=0)
)

print("\nNormalized Dataset:")
print(X_normalized)

average_marks = np.mean(X, axis=1)

predictions = np.where(average_marks >= 50, 1, 0)

print("\nPredicted Results:")
print(predictions)

accuracy = np.mean(predictions == y) * 100

print("\nAccuracy of Predictions:")
print(accuracy, "%")

Features (X):
[[78 85 80 90]
 [45 50 40 55]
 [18 72 94 95]
 [50 95 40 58]
 [75 70 68 52]
 [80 35 38 91]
 [25 78 90 72]
 [98 15 50 87]
 [42 55 88 80]
 [60 25 88 60]]

Labels (y):
[1 0 1 1 0 1 1 0 1 0]

Average Marks:
[57.1 58.  67.6 74. ]

Maximum Marks:
[98 95 94 95]

Minimum Marks:
[18 15 38 52]

Number of Passed Students: 6
Number of Failed Students: 4

Marks Above 80:
[85 90 94 95 95 91 90 98 87 88 88]

Marks Below 50:
[45 40 18 40 35 38 25 15 42 25]

Normalized Dataset:
[[0.75       0.875      0.75       0.88372093]
 [0.3375     0.4375     0.03571429 0.06976744]
 [0.         0.7125     1.         1.        ]
 [0.4        1.         0.03571429 0.13953488]
 [0.7125     0.6875     0.53571429 0.        ]
 [0.775      0.25       0.         0.90697674]
 [0.0875     0.7875     0.92857143 0.46511628]
 [1.         0.         0.21428571 0.81395349]
 [0.3        0.5        0.89285714 0.65116279]
 [0.525      0.125      0.89285714 0.18604651]]

Predicted Results:
[1 0 1 1 1 1 1 1 1 1]

Accurac