In [ ]:
import numpy as np

# STUDENT DATASET
data = np.array([
    [78, 85, 80, 90, 1],
    [45, 50, 40, 55, 0],
    [88, 92, 81, 95, 1],
    [60, 65, 58, 62, 1],
    [35, 40, 30, 45, 0],
    [95, 98, 96, 99, 1],
    [55, 52, 60, 58, 1],
    [48, 45, 50, 42, 0],
    [82, 78, 85, 88, 1],
    [70, 72, 68, 75, 1]
])

print("Dataset:\n")
print(data)

Dataset:

[[78 85 80 90  1]
 [45 50 40 55  0]
 [88 92 81 95  1]
 [60 65 58 62  1]
 [35 40 30 45  0]
 [95 98 96 99  1]
 [55 52 60 58  1]
 [48 45 50 42  0]
 [82 78 85 88  1]
 [70 72 68 75  1]]


In [ ]:
# SEPARATE FEATURES (X) AND LABELS (y)

X = data[:, 0:4]
y = data[:, 4]

print("\nFeatures (X):\n")
print(X)

print("\nLabels (y):\n")
print(y)



Features (X):

[[78 85 80 90]
 [45 50 40 55]
 [88 92 81 95]
 [60 65 58 62]
 [35 40 30 45]
 [95 98 96 99]
 [55 52 60 58]
 [48 45 50 42]
 [82 78 85 88]
 [70 72 68 75]]

Labels (y):

[1 0 1 1 0 1 1 0 1 1]


In [ ]:
# AVERAGE, MAXIMUM, AND MINIMUM MARKS

average_marks = np.mean(X, axis=0)
maximum_marks = np.max(X, axis=0)
minimum_marks = np.min(X, axis=0)

subjects = ["Math", "Science", "English", "Computer"]

print("\nAverage Marks:")
for i in range(4):
    print(subjects[i], "=", average_marks[i])

print("\nMaximum Marks:")
for i in range(4):
    print(subjects[i], "=", maximum_marks[i])

print("\nMinimum Marks:")
for i in range(4):
    print(subjects[i], "=", minimum_marks[i])


Average Marks:
Math = 65.6
Science = 67.7
English = 64.8
Computer = 70.9

Maximum Marks:
Math = 95
Science = 98
English = 96
Computer = 99

Minimum Marks:
Math = 35
Science = 40
English = 30
Computer = 42


In [ ]:
# NUMBER OF PASSED AND FAILED STUDENTS

passed = np.sum(y == 1)
failed = np.sum(y == 0)

print("\nNumber of Passed Students:", passed)
print("Number of Failed Students:", failed)


Number of Passed Students: 7
Number of Failed Students: 3


In [ ]:
# STUDENTS SCORING ABOVE 80 AND BELOW 50

above_80 = X[X > 80]
below_50 = X[X < 50]

print("\nMarks Above 80:")
print(above_80)

print("\nMarks Below 50:")
print(below_50)


Marks Above 80:
[85 90 88 92 81 95 95 98 96 99 82 85 88]

Marks Below 50:
[45 40 35 40 30 45 48 45 42]


In [ ]:
# NORMALIZATION OF DATASET
# Formula:
# (X - min) / (max - min)
X_normalized = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

print("\nNormalized Dataset:\n")
print(X_normalized)



Normalized Dataset:

[[0.71666667 0.77586207 0.75757576 0.84210526]
 [0.16666667 0.17241379 0.15151515 0.22807018]
 [0.88333333 0.89655172 0.77272727 0.92982456]
 [0.41666667 0.43103448 0.42424242 0.35087719]
 [0.         0.         0.         0.05263158]
 [1.         1.         1.         1.        ]
 [0.33333333 0.20689655 0.45454545 0.28070175]
 [0.21666667 0.0862069  0.3030303  0.        ]
 [0.78333333 0.65517241 0.83333333 0.80701754]
 [0.58333333 0.55172414 0.57575758 0.57894737]]


In [ ]:
# SIMPLE PREDICTION LOGIC

average_student_marks = np.mean(X, axis=1)

predictions = np.where(average_student_marks >= 60, 1, 0)

print("\nPredictions:")
print(predictions)


Predictions:
[1 0 1 1 0 1 0 0 1 1]


In [ ]:
# ACCURACY CALCULATION
accuracy = np.mean(predictions == y) * 100

print("\nAccuracy of Predictions:", accuracy, "%")


Accuracy of Predictions: 90.0 %
