In [4]:
import numpy as np
arr1 = np.arange(1, 11)        # 1D array 1–10
arr2 = np.arange(1, 10).reshape(3, 3)  # 3x3 array
zeros = np.zeros((4, 4))
ones = np.ones((2, 5))

print(arr1)
print(arr2)
print(zeros)
print(ones)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)
print("Total elements:", arr.size)
print("Data type:", arr.dtype)
print("Dimensions:", arr.ndim)

Shape: (2, 3)
Total elements: 6
Data type: int64
Dimensions: 2


In [6]:
arr = np.array([10, 20, 30, 40, 50, 60])

print("First:", arr[0])
print("Last:", arr[-1])
print("Third:", arr[2])

print("Greater than 30:", arr[arr > 30])

First: 10
Last: 60
Third: 30
Greater than 30: [40 50 60]


In [7]:
arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[1:5])
print(arr[::-1])
print(arr[::2])

matrix = np.arange(1, 10).reshape(3, 3)

print("First row:", matrix[0])
print("Second column:", matrix[:, 1])
print("Last two rows:", matrix[1:])

[20 30 40 50]
[60 50 40 30 20 10]
[10 30 50]
First row: [1 2 3]
Second column: [2 5 8]
Last two rows: [[4 5 6]
 [7 8 9]]


In [8]:
arr = np.array([1, 2, 3, 4, 5])

print(arr * 5)
print(arr + 10)
print(arr ** 2)

[ 5 10 15 20 25]
[11 12 13 14 15]
[ 1  4  9 16 25]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr + 10)
print(arr * 2)

[[11 12 13]
 [14 15 16]]
[[ 2  4  6]
 [ 8 10 12]]


In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Addition:\n", A + B)
print("Subtraction:\n", A - B)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]


In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Dot Product:\n", np.dot(A, B))
print("Transpose:\n", A.T)

Dot Product:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]


In [12]:
rand_int = np.random.randint(1, 101, (4, 4))
rand_float = np.random.rand(4, 4)

print(rand_int)
print(rand_float)

print("Max:", rand_int.max())
print("Min:", rand_int.min())
print("Average:", rand_int.mean())

[[44 93 39 27]
 [92 39 75 19]
 [40 31 18  6]
 [36 70 60 29]]
[[0.73443026 0.08923521 0.27299549 0.19429661]
 [0.01941459 0.2924638  0.77467818 0.62536543]
 [0.81733646 0.29142145 0.11346759 0.54124191]
 [0.37739158 0.1541257  0.05315957 0.72721026]]
Max: 93
Min: 6
Average: 44.875


In [13]:
marks = np.array([78, 85, 90, 45, 60, 30, 88, 92, 55, 70])

print("Average:", marks.mean())
print("Highest:", marks.max())
print("Lowest:", marks.min())

print("Above 80:", np.sum(marks > 80))
print("Failed (<50):", marks[marks < 50])

Average: 69.3
Highest: 92
Lowest: 30
Above 80: 4
Failed (<50): [45 30]


In [14]:
img = np.random.randint(0, 256, (5, 5))

print(img)
print("Brightest:", img.max())
print("Darkest:", img.min())
print("Shape:", img.shape)

[[ 79  87  36 131 229]
 [ 86 209 151 191 254]
 [223  86  47 244 175]
 [ 16 174  16  64 124]
 [  9 126 226 234  48]]
Brightest: 254
Darkest: 9
Shape: (5, 5)


In [15]:
data = np.array([10, 20, 30, 40, 50])

normalized = (data - data.min()) / (data.max() - data.min())

print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [16]:
# Age, Salary, Purchased
data = np.array([
    [25, 50000, 0],
    [30, 60000, 1],
    [35, 65000, 1],
    [40, 70000, 0],
    [28, 52000, 1]
])

X = data[:, :2]   # Features
y = data[:, 2]    # Labels

print("Features:\n", X)
print("Labels:\n", y)

print("Average Salary:", np.mean(data[:, 1]))
print("Highest Age:", np.max(data[:, 0]))
print("Shape:", data.shape)

Features:
 [[   25 50000]
 [   30 60000]
 [   35 65000]
 [   40 70000]
 [   28 52000]]
Labels:
 [0 1 1 0 1]
Average Salary: 59400.0
Highest Age: 40
Shape: (5, 3)
